# Generated by Django 5.0.6 on 2024-09-22 11:17

import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(auto_created=True, default='a7f9c4b5-cd72-4fd2-8438-912dfc40db2b', unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=thumbnails.fields.ImageField(upload_to=''),
        ),
    ]
