# Generated by Django 5.0.6 on 2024-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_image_name_image_uuid_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
