# Generated by Django 5.0.6 on 2024-09-22 18:15

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_image_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=thumbnails.fields.ImageField(upload_to='images'),
        ),
    ]
